package com.xds.project.data.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xds.project.data.beanv2.CourseGroup;
import com.xds.project.data.beanv2.CourseV2;
import com.xds.project.data.beanv2.Things;
import com.xds.project.data.beanv2.SelfStudy;
import com.xds.project.entity.User;

import com.xds.project.data.greendao.CourseGroupDao;
import com.xds.project.data.greendao.CourseV2Dao;
import com.xds.project.data.greendao.ThingsDao;
import com.xds.project.data.greendao.SelfStudyDao;
import com.xds.project.data.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseGroupDaoConfig;
    private final DaoConfig courseV2DaoConfig;
    private final DaoConfig thingsDaoConfig;
    private final DaoConfig selfStudyDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CourseGroupDao courseGroupDao;
    private final CourseV2Dao courseV2Dao;
    private final ThingsDao thingsDao;
    private final SelfStudyDao selfStudyDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseGroupDaoConfig = daoConfigMap.get(CourseGroupDao.class).clone();
        courseGroupDaoConfig.initIdentityScope(type);

        courseV2DaoConfig = daoConfigMap.get(CourseV2Dao.class).clone();
        courseV2DaoConfig.initIdentityScope(type);

        thingsDaoConfig = daoConfigMap.get(ThingsDao.class).clone();
        thingsDaoConfig.initIdentityScope(type);

        selfStudyDaoConfig = daoConfigMap.get(SelfStudyDao.class).clone();
        selfStudyDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        courseGroupDao = new CourseGroupDao(courseGroupDaoConfig, this);
        courseV2Dao = new CourseV2Dao(courseV2DaoConfig, this);
        thingsDao = new ThingsDao(thingsDaoConfig, this);
        selfStudyDao = new SelfStudyDao(selfStudyDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(CourseGroup.class, courseGroupDao);
        registerDao(CourseV2.class, courseV2Dao);
        registerDao(Things.class, thingsDao);
        registerDao(SelfStudy.class, selfStudyDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        courseGroupDaoConfig.clearIdentityScope();
        courseV2DaoConfig.clearIdentityScope();
        thingsDaoConfig.clearIdentityScope();
        selfStudyDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CourseGroupDao getCourseGroupDao() {
        return courseGroupDao;
    }

    public CourseV2Dao getCourseV2Dao() {
        return courseV2Dao;
    }

    public ThingsDao getThingsDao() {
        return thingsDao;
    }

    public SelfStudyDao getSelfStudyDao() {
        return selfStudyDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
